config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  
  resources :questions do
    put :hide, on: :member
  end

  resource :session, only: %i[new create destroy]
  resources :users, except: %i[index], param: :nickname
  resources :hashtags, only: :show, param: :hashtag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :question_hashtags
  has_many :questions, through: :question_hashtags, source: :question

  validates :body, presence: true, uniqueness: true

  before_save :to_downcase

  private

  def to_downcase
    body&.downcase!
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_many :question_hashtags, dependent: :destroy
  has_many :hashtags, through: :question_hashtags, source: :hashtag

  validates :body, presence: true, length: { in: 3..280 }

  after_create_commit :create_all_hashtags

  private

  def create_all_hashtags
    self.hashtags = body.scan(/#[\wА-Яа-яЁё]+/).map { |tag| Hashtag.create_or_find_by(body: tag[1..-1]) }
  end
end

app/models/question_hashtag.rb
class QuestionHashtag < ApplicationRecord
  belongs_to :question, optional: true
  belongs_to :hashtag
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic

  has_many :questions, dependent: :delete_all

  before_validation :downcase_nickname

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :nickname, presence: true, uniqueness: true, length: { in: 3..40 },
            format: { with: /\A[\w]+\z/ }
  validates :header_color, format: { with: /\A#\h{3}{1,2}\z/ }
  validates :name, presence: true, length: { in: 2..15 }

  has_secure_password
  gravtastic(secure: true, filetype: :png, size: 100, default: 'retro')
  
  private

  def downcase_nickname
    nickname&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :select_hashtags
  helper_method :find_hashtag_by_body

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end

  def select_hashtags(text)
    text.scan(/#[\wА-Яа-яЁё]+/).map { |tag| tag[1..-1] }
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = params[:hashtag]
    @questions = Question.joins(:hashtags).where(hashtags: { body: @hashtag}).order(created_at: :desc)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy hide edit]
  before_action :set_question_for_current_user, only: %i[update destroy hide edit]

  def create 
    @question = Question.new(author: current_user)

    if @question.update(question_params_for_create)
      redirect_to user_path(@question.user.nickname), notice: 'Вопрос создан!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили формы для создания вопроса'
      render :new
    end
  end

  def update
    @question.update(question_params_for_update)
    redirect_to user_path(@question.user), notice: 'Вопрос сохранен!'
  end

  def destroy
    @user = @question.user
    @question.destroy
    redirect_to user_path(@user), notice: 'Вопрос удален!'
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.order(created_at: :desc).first(10)
    @users = User.order(created_at: :desc).first(10)
    @hashtags = Hashtag.all
  end

  def questions_by_hashtag
    @hashtag = params[:hashtag]
    @questions = Question.joins(:hashtags).where(hashtags: { body: @hashtag}).order(created_at: :desc)
  end

  def new
    @user = User.find_by!(nickname: params[:nickname])
    @question = Question.new(user: @user)
  end

  def edit
    @nick = current_user.nickname
  end

  def hide
    @question.update(hidden: true)
    redirect_to question_path(@question)
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def question_params_for_create
    params.require(:question).permit(:user_id, :body)
  end

  def question_params_for_update
    params.require(:question).permit(:hidden, :answer)
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)
    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Вы авторизировались!'
    else
      flash.now[:alert] = 'Некорректные данные учетной записи'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Вы вышли из учетной записи!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit udpate destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Вы успешно зарегистрировались!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили формы для регистрации'
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Профиль обновлен!'
    else
      flash.now[:alert] = 'При попытке сохранить изменения возникла ошибка'
      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удален'
  end

  def show
    @user = User.find_by!(nickname: params[:nickname])
    @questions = @user.questions.order("created_at DESC")
  end

  private

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.find_by!(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation, :header_color
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end

  def slice_by_hashtags(text_line)
    text_line.split(/#[\wА-Яа-яЁё]+/)
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/question_hashtags_helper.rb
module QuestionHashtagsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def all_hashtags(text)
    text.scan(/#[\wА-Яа-яЁё]+/).map { |tag| tag[1..-1].downcase }
  end

  def fhashtag(hashtag)
    "##{hashtag}"
  end

  def questions_hashtag_path(hashtag)
    "/hashtags/#{hashtag}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def fnickname(nickname)
    "@#{nickname}"
  end


  def header_color_checking(user)
    user&.header_color || '#0BA5BE'
  end
end

app/views/hashtags/_hashtag.html.erb
<span class="hashtag">
  <%= link_to fhashtag(hashtag), hashtag_path(hashtag.downcase), class: 'hashtag without-underline' %>
</span>

app/views/hashtags/show.html.erb
<div class="container mt-sm mb-sm">
  <h2 class="title-lg">
    Вопросы с хештегом
    <span class="hashtag">
      <%= fhashtag(@hashtag) %>
    </span>
  </h2>
</div>

<% @questions.each do |question| %>
  <% if question.hidden? %>
    <div class="container hidden mb-sm">
      <%= render question%>
    </div>
  <% else %>
    <div class="container mb-sm">
      <%= render question%>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Askme</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="wrapper">
  <%= tag.div class: "navbar", style: "background-color: #{header_color_checking(current_user)};" do %>
    <p class="title-sm text-bold">
      <%= link_to 'Ask me!', root_path, class: 'white-link' %>
    </p>
    <div>
      <% if current_user.present? %>
        <%= link_to fnickname(current_user.nickname), user_path(current_user.nickname), title: 'Профиль', class: 'mr-sm white-link' %>
        <%= link_to fa_icon('cog'), edit_user_path(current_user.nickname), title: 'Настройки', class: 'white-link mr-sm' %>
        <%= button_to fa_icon('sign-out'), session_path, title: 'Выход', method: :delete,
                      class: 'white-link', form: {data: {turbo_confirm: 'Вы уверены, что хотите выйти?'}} %>
      <% else %>
        <%= link_to 'Регистрация', new_user_path, class: 'white-link mr-sm' %>
        <%= link_to fa_icon('sign-in'), new_session_path, title: 'Вход', class: 'white-link' %>
      <% end %>
    </div>
  <% end %>

  <% if flash[:notice].present? %>
    <p class="mb mt message message-notice text-center">
      <%= flash[:notice] %>
    </p>
  <% elsif flash[:alert].present? %>
    <p class="mb mt message message-alert text-center">
      <%= flash[:alert] %>
    </p>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question, data: {turbo: false } do |form| %>
  <%= form.hidden_field :user_id %>

  <p class="mb-md"><%= form.label :body, 'Текст вопроса' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, 'Ответ' %></p>
    <p class="mt"><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <% end %>

  <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %></p>
<% end %>

app/views/questions/_question.html.erb
<h2 class="title-lg mb title-sm">
  Вопрос <%= link_to "##{question.id}", question_path(question), class: 'without-underline text-orange' %>

  <% if question.author.present? %>
    <span>
      от <%= link_to fnickname(question.author.nickname), user_path(question.author.nickname),
                     class: 'text-orange without-underline' %>
    </span>
  <% else %>
    <span>
      от гостя
    </span>
  <% end %>

  <span>
      для <%= link_to fnickname(question.user.nickname), user_path(question.user.nickname),
                      class: 'text-green without-underline' %>
    </span>
</h2>

<div class="mb-lg text-orange">
  <% lines = question.body.split(/\n/) %>
  <% lines.each do |text_line| %>
    <% line_parts = slice_by_hashtags(text_line) %>
    <% line_hashtags = select_hashtags(text_line) %>
    <% pair_quantity = ((line_hashtags.size + line_parts.size).to_f / 2).ceil %>

    <p>
      <% pair_quantity.times do |index| %>
        <% unless line_parts[index].nil? %>
          <%= h(line_parts[index]) %>
        <% end %>

        <% unless line_hashtags[index].nil? %>
          <%= render partial: 'hashtags/hashtag', locals: { hashtag: line_hashtags[index] } %>
        <% end %>
      <% end %>
    </p>
  <% end %>
</div>

<% if question.answer.present? %>
  <div class="mb-sm mt-lg text-green">
    <%= simple_format h(question.answer) %>
  </div>
<% end %>

<div class="question-footer text-sm">
  <div class="text-gray mt">
    <%= l(question.created_at, format: :short) %>
  </div>

  <% if current_user == question.user && current_user.present? %>
    <div class="mt">
      <% edit_icon = (question.answer.present? ? 'pencil' : 'reply') %>

      <%= link_to fa_icon(edit_icon), edit_question_path(question), title: 'Изменить вопрос', class: 'mr-sm' %>
      <%= button_to fa_icon('trash-o'), question_path(question), method: :delete, class: 'mr-sm',
                    title: 'Удалить вопрос', form: {data: {turbo_confirm: 'Точно удалить вопрос?'}} %>

      <% unless question.hidden %>
        <%= button_to fa_icon('eye-slash'), hide_question_path(question), method: :put, title: 'Скрыть' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <div class="mb-lg">
    <%= link_to fa_icon('arrow-left'), :back, title: 'Назад' %>
  </div>

  <h2 class="title-lg mb">Редактирование вопроса <%= @question.id %></h2>

  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container mb-sm">
  <h2 class="title-lg mb text-center">
    Недавно добавились
  </h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: {user: user} %>
    <% end %>
  </div>
</div>

<div class="container mb-sm">
  <h2 class="title-lg mb text-center">
    Хештеги
  </h2>

  <div class="hashtags-box">
    <% @hashtags.each do |hashtag| %>
      <div>
        <%= render partial: 'hashtags/hashtag', locals: {hashtag: hashtag.body} %>
      </div>
    <% end %>
  </div>
</div>

<div class="container mt-sm mb-sm">
  <h2 class="title-lg">
    <%= inclination(@questions.count, 'Последний', 'Последние', 'Последние') %>
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
  </h2>
</div>

<% @questions.each do |question| %>
  <% if question.hidden? %>
    <div class="container hidden mb-sm">
      <%= render question%>
    </div>
  <% else %>
    <div class="container mb-sm">
      <%= render question%>
    </div>
  <% end %>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">Новый вопрос</h2>
  <p class="mb">для <%= link_to fnickname(@question.user.nickname), user_path(@question.user.nickname), class: 'without-underline text-orange' %></p>

  <%= render 'users/errors_output', obj: @question %>
  <%= render 'form', question: @question %>
</div>

app/views/questions/questions_by_hashtag.html.erb
<div class="container mt-sm mb-sm">
  <h2 class="title-lg">
    Вопросы с хештегом
    <span class="hashtag">
      <%= fhashtag(@hashtag) %>
    </span>
  </h2>
</div>

<% @questions.each do |question| %>
  <% if question.hidden? %>
    <div class="container hidden mb-sm">
      <%= render question%>
    </div>
  <% else %>
    <div class="container mb-sm">
      <%= render question%>
    </div>
  <% end %>
<% end %>

app/views/questions/show.html.erb
<div class="container">
    <div class="mb-lg">
      <%= link_to fa_icon('arrow-left'), :back, title: 'Назад' %>
    </div>

    <%= render 'question', question: @question %>

    <p class="mt"><%= link_to "Все вопросы", questions_path %></p>
</div>

app/views/users/_errors_output.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <div class="mt">
      <p class="mb-sm text-error">
        <%= message %>
      </p>
    </div>
  <% end %>
<% end %>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user <%= background_class %> rounded mr ml">
  <a href="<%= user_path(user.nickname) %>">
    <h1>
      <%= image_tag user.gravatar_url, title: fnickname(user.nickname), class: 'rounded' %>
    </h1>
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="mb-lg">
    <%= link_to fa_icon('arrow-left'), :back, title: 'Назад' %>
  </div>

  <h2 class="title">
    Редактирование пользователя
  </h2>

  <div class="mt">
    <p>
      <%= image_tag @user.gravatar_url, title: fnickname(@user.nickname), class: 'rounded' %>
    </p>

    <p class="text-sm mt-md mb-lg">
      Чтобы поменять аватар - зарегистрируйтесь на
      <%= link_to 'Gravatar', 'https://ru.gravatar.com/', class: 'without-underline title-sm text-orange' %>
    </p>
  </div>

  <%= render 'errors_output', obj: @user %>

  <div class="mt">
    <%= form_with model: @user, method: :patch, url: user_path(current_user.nickname), data: {turbo: false } do |form| %>
      <p>
        <%= form.label :name, 'Ваше имя' %>
      </p>
      <p>
        <%= form.text_field :name, class: 'form-text-field' %>
      </p>

      <p class="mt">
        <%= form.label :nickname, 'Ваш ник' %>
      </p>
      <p>
        <%= form.text_field :nickname, class: 'form-text-field' %>
      </p>

      <p class="mt">
        <%= form.label :header_color, 'Цвет шапки вашего профиля' %>
      </p>
      <p class="mt-sm">
        <%= form.color_field :header_color %>
      </p>

      <p class="mt-lg">
        Если не хотите менять пароль - оставьте эти поля пустыми
      </p>

      <p class="mt">
        <%= form.label :password, 'Новый пароль' %>
      </p>
      <p>
        <%= form.password_field :password, class: 'form-text-field' %>
      </p>

      <p class="mt">
        <%= form.label :password_confirmation, 'Подтверждение пароля' %>
      </p>
      <p>
        <%= form.password_field :password_confirmation, class: 'form-text-field' %>
      </p>

      <p class="mt-lg">
        <%= form.submit 'Сохранить', class: 'button button-main' %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">
    Присоединяйся и спрашивай!
  </h2>

  <div class="mt">
    <%= form_with model: @user do |form| %>
      <p>
        <%= form.label :name, 'Ваше имя' %>
      </p>
      <p>
        <%= form.text_field :name, class: 'form-text-field' %>
      </p>

      <p class="mt">
        <%= form.label :nickname, 'Ваш ник' %>
      </p>
      <p>
        <%= form.text_field :nickname, class: 'form-text-field' %>
      </p>

      <p class="mt">
        <%= form.label :email, 'Ваш email' %>
      </p>
      <p>
        <%= form.text_field :email, class: 'form-text-field' %>
      </p>

      <p class="mt">
        <%= form.label :password, 'Ваш пароль' %>
      </p>
      <p>
        <%= form.password_field :password, class: 'form-text-field' %>
      </p>

      <p class="mt-lg">
        <%= form.submit 'Зарегистрироваться', class: 'button button-main' %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-box">
  <h2 class="title-lg mt-lg">
    <%= @user.name %>

    <div class="mt-lg mb-md">
      <%= render partial: 'users/user_avatar', locals: {user: @user} %>
    </div>

    <p class="text-bold mt mb-lg">
      <%= fnickname(@user.nickname) %>
    </p>
  </h2>
</div>

<% if @questions.empty? %>
  <div class="container void-space">
    <p class="mt white-text all-center">
      Кажется у этого пользователя нет вопросов...
    </p>

    <p class="mt-lg all-center">
      <%= link_to "Задай первый вопрос!", new_question_path(nickname: @user.nickname),
                  class: 'button button-yellow' %>
    </p>
  </div>
<% else %>
  <div class="container mb-lg all-center">
    <p class="mt-lg">
      <%= link_to "Спросить что-то", new_question_path(nickname: @user.nickname),
                  class: 'button button-yellow' %>
    </p>
  </div>

  <div class="container mb-sm">
    <h2 class="title-lg mb text-center">
      <%= @questions.count %>
      <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
    </h2>
  </div>

  <% @questions.each do |question| %>
    <% if question.hidden? %>
      <div class="container hidden mb-sm">
        <%= render question%>
      </div>
    <% else %>
      <div class="container mb-sm">
        <%= render question%>
      </div>
    <% end %>
  <% end %>

<% end %>